// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT9Fws2xnrwcnJLgHWWAAws9veWdX-OW8',
    appId: '1:105879476758:web:5c4a574751da5ff617f337',
    messagingSenderId: '105879476758',
    projectId: 'c-algovisualizer',
    authDomain: 'c-algovisualizer.firebaseapp.com',
    storageBucket: 'c-algovisualizer.firebasestorage.app',
  );

  static FirebaseOptions get currentPlatform {
    return web;
  }
}
